### ISSUE TITLE
Subtracting one causes rounding errors to favor the user

### ISSUE THREAD

**Issue by samczsun** [balancer-labs/configurable-rights-pool#18]
https://github.com/balancer-labs/configurable-rights-pool/blob/be02d74740add29aed928e8dc598356f0181f961/libraries/SmartPoolManager.sol#L475-L476

The ratio is the percentage of the pool's tokens the user can withdraw. Subtracting one from the pool's total makes the user's share larger, which would entitle them to more funds instead of less

**Comment by EndymionJkb** [comment]
Managed to confuse myself on the math. The rest of them are right? There are 4 rounding adjustments (this was from the Open Zeppelin core audit of similar code).

**Comment by samczsun** [comment]
Seems like the one to join a pool is backwards too. The two other ones seem fine though.

https://github.com/balancer-labs/configurable-rights-pool/blob/be02d74740add29aed928e8dc598356f0181f961/libraries/SmartPoolManager.sol#L421-L422

I'd be interested in seeing the code you were inspired by, since manually offsetting every calculation seems like a very heavy-handed way to handle rounding errors

**Comment by EndymionJkb** [comment]
It was in the last [security audit](https://blog.openzeppelin.com/balancer-contracts-audit/) (of the core code): just search for "rounding" - the point right to the line. Of course, I could have misinterpreted it.

**Comment by samczsun** [comment]
It seems like the recommendation was add 1 to the _result_ of the multiplication or division:

>For example, in the joinPool function, consider adding 1 to the output of bdiv on line 358 to counteract any rounding-down that may have ocurred during the execution of bdiv, and consider adding 1 to the output of bmul on line 381 to counteract any rounding-down that may have ocurred during the execution of bmul. This would ensure that all calls to the joinPool function have arithmetic errors that are in favor of the pool. While this may slightly increase the absolute size of the errors, it enforces that the direction of the errors favors the security of the pool.

**Comment by EndymionJkb** [comment]
I did read it wrong, then. So in joinPool:
Instead of "uint ratio = BalancerSafeMath.bdiv(poolAmountOut, poolTotal - 1);" =>
                   uint ratio = BalancerSafeMath.bdiv(poolAmountOut, poolTotal) + 1;

And "uint tokenAmountIn = BalancerSafeMath.bmul(ratio, bal + 1);" =>
         uint tokenAmountIn = BalancerSafeMath.bmul(ratio, bal) + 1;

And in exitPool, reversed? :
"uint ratio = BalancerSafeMath.bdiv(pAiAfterExitFee, poolTotal + 1);" => 
uint ratio = BalancerSafeMath.bdiv(pAiAfterExitFee, poolTotal) - 1;

And "uint tokenAmountOut = BalancerSafeMath.bmul(ratio, bal - 1);" =>
         uint tokenAmountOut = BalancerSafeMath.bmul(ratio, bal) - 1;

**Comment by samczsun** [comment]
Oh actually, you probably don't need to subtract anything in `exitPool` because division rounds down which implicitly favors the pool since a smaller ratio means less funds going out. Furthermore, if you want to subtract you'll have to deal with the underflow case (i.e. if the `bmul` or `bdiv` result in 0)

**Comment by samczsun** [comment]
Resolved in https://github.com/balancer-labs/configurable-rights-pool/commit/94d6471cd6fc5d796fdf8fcf56ea5428919afcf4
