### ISSUE TITLE
The ConfigurableRightsPool is vulnerable to tokens which allow callbacks

### ISSUE THREAD

**Issue by samczsun** [balancer-labs/configurable-rights-pool#19]
When joining or exiting a pool, a lock is obtained on the ConfigurableRightsPool instance but not the underlying Balancer pool. If one of the constituent tokens allows callbacks (for example, if the token supports the ERC 777 or ERC 223 standard), then it may be possible to perform a swap while joining or exiting the pool.

Consider the following scenario:

A particular `ConfigurableRightsPool` is composed of three stablecoins: DAI, LAI, and USDC. LAI is a fictional stablecoin which supports the ERC 777 standard. The denormalized weight of each token is 10 and there is 100,000 USD of each token in the pool. A total of 10,000 pool tokens have already been minted, and the swap fee is 2%.

The attacker first calls `joinPool` to mint 5,000 pool tokens. This locks the `ConfigurableRightsPool` but not the underlying Balancer pool. If we do the math, we find that the attacker will need to transfer 50,000 USD of each stablecoin.

First, the pool transfers 50,000 DAI into the pool. Note that at the moment, there is an imbalance between DAI/LAI and DAI/USDC.

Next, the pool transfers 50,000 LAI into the pool. Per the specification, LAI will trigger a callback to the attacker before any tokens are transferred. The attacker uses this callback to swap 25,000 USDC to DAI. Due to the current imbalance between DAI/USDC, the attacker will receive ~29,518 DAI.

Finally, the pool transfers 50,000 USDC into the pool and mints the attacker their pool tokens. The pool state is now as follows:

```
Total supply: 15,000
DAI balance: 120,482
LAI balance: 150,000
USDC balance: 150,000
```

If the attacker simply exits the pool at this point, they will receive a proportional amount of the underlying tokens. Specifically, they'll receive:
~40,160 DAI
50,000 LAI
50,000 USDC

Notice that the attacker has ended up with ~69,678 DAI despite starting with 50,000 DAI. An instant profit of ~19,678 DAI was made. This attack could be further optimized by balancing the pool before exiting, or performing the same attack while exiting.

**Comment by samczsun** [comment]
Some possible remediations:
- Just warn people that tokens with callbacks aren't supported
- Assert that balances are as expected after transferring all tokens

But those don't solve the general problem of "it's possible to alter the underlying pool while in the CRP", which is unfortunate

**Comment by EndymionJkb** [comment]
Could we turn swapping off on the underlying pool during joins?

**Comment by EndymionJkb** [comment]
Otherwise, you're saying that on any join, I would need to get the beginning balances of the underlying pool tokens, and then at the end, after the transfers, check that the balances all equal "starting balance + tokenAmountIn"? Would that work? And what if somebody *else* does a swap - couldn't that cause a revert when there wasn't an attack?

**Comment by samczsun** [comment]
Resolved in https://github.com/balancer-labs/configurable-rights-pool/commit/94d6471cd6fc5d796fdf8fcf56ea5428919afcf4
